-- Menu structure: categories -> items -> modifier groups -> modifiers.
--
-- Prices are integer cents everywhere. Splitting a bill three ways is the core money
-- operation here, and doing that in cents makes the remainder explicit rather than
-- something a decimal type rounds away silently.

CREATE TABLE category (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(64) NOT NULL UNIQUE,
    sort_order INT         NOT NULL DEFAULT 0
);

CREATE TABLE menu_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT       NOT NULL REFERENCES category (id),
    name        VARCHAR(128) NOT NULL,
    description VARCHAR(512),
    price_cents BIGINT       NOT NULL CHECK (price_cents >= 0),
    -- The 86 flag. Flipped by the kitchen mid-service; drives cache invalidation.
    available   BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order  INT          NOT NULL DEFAULT 0,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX ix_menu_item_category ON menu_item (category_id);

CREATE TABLE modifier_group (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id BIGINT      NOT NULL REFERENCES menu_item (id) ON DELETE CASCADE,
    name         VARCHAR(64) NOT NULL,
    -- min_select = 0 makes the group optional; 1 forces a choice (e.g. steak doneness).
    min_select   INT         NOT NULL DEFAULT 0,
    max_select   INT         NOT NULL DEFAULT 1,
    sort_order   INT         NOT NULL DEFAULT 0,
    CHECK (min_select >= 0 AND max_select >= min_select)
);

CREATE INDEX ix_modifier_group_item ON modifier_group (menu_item_id);

CREATE TABLE modifier (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modifier_group_id BIGINT      NOT NULL REFERENCES modifier_group (id) ON DELETE CASCADE,
    name              VARCHAR(64) NOT NULL,
    price_delta_cents BIGINT      NOT NULL DEFAULT 0,
    available         BOOLEAN     NOT NULL DEFAULT TRUE,
    sort_order        INT         NOT NULL DEFAULT 0
);

CREATE INDEX ix_modifier_group ON modifier (modifier_group_id);

INSERT INTO category (name, sort_order) VALUES
    ('Starters', 1),
    ('Mains', 2),
    ('Sides', 3),
    ('Desserts', 4),
    ('Drinks', 5);

INSERT INTO menu_item (category_id, name, description, price_cents, sort_order) VALUES
    ((SELECT id FROM category WHERE name = 'Starters'), 'Soup of the Day', 'Ask your server; always vegetarian.', 650, 1),
    ((SELECT id FROM category WHERE name = 'Starters'), 'Garlic Focaccia', 'Rosemary, sea salt, olive oil.', 550, 2),
    ((SELECT id FROM category WHERE name = 'Starters'), 'Burrata', 'Heritage tomato, basil, aged balsamic.', 950, 3),
    -- The salmon is the demo's canary: 86'ing it exercises the whole invalidation path.
    ((SELECT id FROM category WHERE name = 'Mains'), 'Pan-Seared Salmon', 'Crushed new potatoes, salsa verde.', 1850, 1),
    ((SELECT id FROM category WHERE name = 'Mains'), 'Ribeye Steak', '300g, dry-aged 35 days.', 2650, 2),
    ((SELECT id FROM category WHERE name = 'Mains'), 'Wild Mushroom Risotto', 'Parmesan, truffle oil.', 1550, 3),
    ((SELECT id FROM category WHERE name = 'Mains'), 'Buttermilk Chicken Burger', 'Slaw, pickles, brioche bun.', 1450, 4),
    ((SELECT id FROM category WHERE name = 'Sides'), 'Triple-Cooked Chips', NULL, 500, 1),
    ((SELECT id FROM category WHERE name = 'Sides'), 'Tenderstem Broccoli', 'Chilli, lemon, almonds.', 550, 2),
    ((SELECT id FROM category WHERE name = 'Sides'), 'House Salad', NULL, 450, 3),
    ((SELECT id FROM category WHERE name = 'Desserts'), 'Sticky Toffee Pudding', 'Salted caramel, clotted cream.', 750, 1),
    ((SELECT id FROM category WHERE name = 'Desserts'), 'Lemon Tart', 'Torched meringue.', 700, 2),
    ((SELECT id FROM category WHERE name = 'Drinks'), 'Still Water', '750ml', 300, 1),
    ((SELECT id FROM category WHERE name = 'Drinks'), 'House Red', '175ml glass', 750, 2),
    ((SELECT id FROM category WHERE name = 'Drinks'), 'Craft Lager', '330ml', 600, 3),
    ((SELECT id FROM category WHERE name = 'Drinks'), 'Flat White', NULL, 350, 4);

-- Steak doneness is mandatory (min_select = 1): the kitchen cannot start without it.
INSERT INTO modifier_group (menu_item_id, name, min_select, max_select, sort_order) VALUES
    ((SELECT id FROM menu_item WHERE name = 'Ribeye Steak'), 'Cooked to', 1, 1, 1),
    ((SELECT id FROM menu_item WHERE name = 'Ribeye Steak'), 'Sauce', 0, 1, 2),
    ((SELECT id FROM menu_item WHERE name = 'Pan-Seared Salmon'), 'Extras', 0, 2, 1),
    ((SELECT id FROM menu_item WHERE name = 'Buttermilk Chicken Burger'), 'Extras', 0, 3, 1),
    ((SELECT id FROM menu_item WHERE name = 'Flat White'), 'Milk', 0, 1, 1);

INSERT INTO modifier (modifier_group_id, name, price_delta_cents, sort_order)
SELECT g.id, v.name, v.price, v.sort_order
FROM modifier_group g
JOIN menu_item i ON i.id = g.menu_item_id
JOIN (VALUES
    ('Ribeye Steak',              'Cooked to', 'Rare',              0,   1),
    ('Ribeye Steak',              'Cooked to', 'Medium rare',       0,   2),
    ('Ribeye Steak',              'Cooked to', 'Medium',            0,   3),
    ('Ribeye Steak',              'Cooked to', 'Well done',         0,   4),
    ('Ribeye Steak',              'Sauce',     'Peppercorn',        150, 1),
    ('Ribeye Steak',              'Sauce',     'Béarnaise',         150, 2),
    ('Pan-Seared Salmon',         'Extras',    'Extra salsa verde', 100, 1),
    ('Pan-Seared Salmon',         'Extras',    'Lemon butter',      100, 2),
    ('Buttermilk Chicken Burger', 'Extras',    'Smoked bacon',      200, 1),
    ('Buttermilk Chicken Burger', 'Extras',    'Extra cheese',      150, 2),
    ('Buttermilk Chicken Burger', 'Extras',    'Hot honey',         100, 3),
    ('Flat White',                'Milk',      'Oat milk',          50,  1),
    ('Flat White',                'Milk',      'Almond milk',       50,  2)
) AS v(item_name, group_name, name, price, sort_order)
  ON v.item_name = i.name AND v.group_name = g.name;
