-- Orders and their lines.
--
-- The table is customer_order rather than "order": ORDER is a reserved word in SQL, and
-- a table by that name has to be quoted at every single use site.

CREATE TABLE customer_order (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id       BIGINT      NOT NULL,
    table_code     VARCHAR(16) NOT NULL,
    session_id     UUID        NOT NULL,
    status         VARCHAR(24) NOT NULL DEFAULT 'PLACED',
    placed_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    subtotal_cents BIGINT      NOT NULL DEFAULT 0 CHECK (subtotal_cents >= 0),
    -- Optimistic locking. Two kitchen terminals can advance the same ticket at the same
    -- instant; the version column turns that into a detectable conflict rather than a
    -- lost update.
    version        BIGINT      NOT NULL DEFAULT 0
);

CREATE INDEX ix_order_table ON customer_order (table_id);
CREATE INDEX ix_order_status ON customer_order (status);
-- The kitchen queue is "everything not finished, oldest first".
CREATE INDEX ix_order_placed_at ON customer_order (placed_at);

CREATE TABLE order_line (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id              BIGINT       NOT NULL REFERENCES customer_order (id) ON DELETE CASCADE,
    menu_item_id          BIGINT       NOT NULL,
    -- Name and price are copied, not referenced. The kitchen ticket must keep showing what
    -- the customer ordered at the price they were quoted, even after the menu changes.
    name                  VARCHAR(128) NOT NULL,
    quantity              INT          NOT NULL CHECK (quantity > 0),
    unit_price_cents      BIGINT       NOT NULL CHECK (unit_price_cents >= 0),
    modifiers_total_cents BIGINT       NOT NULL DEFAULT 0,
    line_total_cents      BIGINT       NOT NULL CHECK (line_total_cents >= 0),
    note                  VARCHAR(255),
    sort_order            INT          NOT NULL DEFAULT 0
);

CREATE INDEX ix_order_line_order ON order_line (order_id);

CREATE TABLE order_line_modifier (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_line_id     BIGINT       NOT NULL REFERENCES order_line (id) ON DELETE CASCADE,
    modifier_id       BIGINT       NOT NULL,
    name              VARCHAR(64)  NOT NULL,
    price_delta_cents BIGINT       NOT NULL DEFAULT 0
);

CREATE INDEX ix_order_line_modifier_line ON order_line_modifier (order_line_id);
