-- Bills and the payments made against them.
--
-- A bill is created lazily the first time someone asks to pay for an order, snapshotting
-- the order subtotal at that moment. Snapshotting rather than re-reading matters: the
-- amount a customer agreed to pay must not move underneath a part-paid split.

CREATE TABLE bill (
    order_id         BIGINT      PRIMARY KEY,
    table_id         BIGINT      NOT NULL,
    table_code       VARCHAR(16) NOT NULL,
    subtotal_cents   BIGINT      NOT NULL CHECK (subtotal_cents >= 0),
    tip_cents        BIGINT      NOT NULL DEFAULT 0 CHECK (tip_cents >= 0),
    -- What is still owed, decremented by each successful payment. Reaching zero is what
    -- moves the order to PAID; individual payments do not.
    outstanding_cents BIGINT     NOT NULL CHECK (outstanding_cents >= 0),
    settled          BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Split bills mean concurrent payers. Optimistic locking turns two simultaneous
    -- payments into one retry rather than a lost decrement of the outstanding balance.
    version          BIGINT      NOT NULL DEFAULT 0
);

CREATE INDEX ix_bill_table ON bill (table_id);

CREATE TABLE payment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT      NOT NULL REFERENCES bill (order_id) ON DELETE CASCADE,
    amount_cents  BIGINT      NOT NULL CHECK (amount_cents > 0),
    tip_cents     BIGINT      NOT NULL DEFAULT 0 CHECK (tip_cents >= 0),
    card_last4    VARCHAR(4),
    status        VARCHAR(16) NOT NULL,
    failure_reason VARCHAR(255),
    reference     VARCHAR(64) NOT NULL UNIQUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX ix_payment_order ON payment (order_id);
