-- The kitchen display's read model: one ticket per order, fanned in from every table.
--
-- This is a projection of events produced by order-service, not a second source of truth.
-- If it is ever lost it can be rebuilt by replaying orders.events from the beginning,
-- which is why every write here is an idempotent upsert keyed by order_id.

CREATE TABLE kitchen_ticket (
    -- order_id is the primary key, not a surrogate: one ticket per order, and using the
    -- order's own id makes a redelivered event an upsert rather than a duplicate row.
    order_id       BIGINT       PRIMARY KEY,
    table_id       BIGINT       NOT NULL,
    table_code     VARCHAR(16)  NOT NULL,
    status         VARCHAR(24)  NOT NULL DEFAULT 'PLACED',
    placed_at      TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    subtotal_cents BIGINT       NOT NULL DEFAULT 0
);

-- The board is "everything unfinished, oldest first", so placed_at carries the sort.
CREATE INDEX ix_kitchen_ticket_placed_at ON kitchen_ticket (placed_at);
CREATE INDEX ix_kitchen_ticket_status ON kitchen_ticket (status);

CREATE TABLE kitchen_ticket_line (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT       NOT NULL REFERENCES kitchen_ticket (order_id) ON DELETE CASCADE,
    name       VARCHAR(128) NOT NULL,
    quantity   INT          NOT NULL,
    -- Flattened for display: the cook reads "Ribeye Steak / Medium rare, Peppercorn",
    -- and never needs to resolve a modifier id.
    modifiers  VARCHAR(512),
    note       VARCHAR(255),
    sort_order INT          NOT NULL DEFAULT 0
);

CREATE INDEX ix_kitchen_ticket_line_order ON kitchen_ticket_line (order_id);
