-- Physical tables and the customer sessions opened against them.

CREATE TABLE restaurant_table (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code              VARCHAR(16)  NOT NULL UNIQUE,
    -- The opaque value encoded in the printed QR sticker. Deliberately not the table
    -- code: codes are guessable, so a guessable QR value would let anyone open a
    -- session on any table without being in the restaurant.
    qr_code           VARCHAR(64)  NOT NULL UNIQUE,
    seats             INT          NOT NULL DEFAULT 2,
    state             VARCHAR(24)  NOT NULL DEFAULT 'FREE',
    attention_flagged BOOLEAN      NOT NULL DEFAULT FALSE,
    attention_note    VARCHAR(255),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE table_session (
    id          UUID         PRIMARY KEY,
    table_id    BIGINT       NOT NULL REFERENCES restaurant_table (id),
    started_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    ended_at    TIMESTAMPTZ
);

-- One open session per table. A second scan while a session is open joins the existing
-- session rather than starting a rival one, so two phones at the same table share a bill.
CREATE UNIQUE INDEX ux_table_session_open
    ON table_session (table_id)
    WHERE ended_at IS NULL;

CREATE INDEX ix_table_session_table ON table_session (table_id);

INSERT INTO restaurant_table (code, qr_code, seats) VALUES
    ('T-01', 'qr-t01-9f3a2b', 2),
    ('T-02', 'qr-t02-4c8d1e', 2),
    ('T-03', 'qr-t03-7b5f0a', 4),
    ('T-04', 'qr-t04-2e9c6d', 4),
    ('T-05', 'qr-t05-8a1b3f', 4),
    ('T-06', 'qr-t06-5d7e2c', 6),
    ('T-07', 'qr-t07-1f4a8b', 6),
    ('T-08', 'qr-t08-6c2d9e', 8);
